# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
# from timezone_field import fields
# import timezone_field.fields
import timezone_field.fields

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('real_name', models.CharField(max_length=100)),
                ('tz', timezone_field.fields.TimeZoneField()),
            ],
            options={
                'verbose_name': 'Members',
                'verbose_name_plural': 'Memberss',
            },
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'time',
                'verbose_name_plural': 'times',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='activity_periods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.time'),
        ),
    ]
