# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-28 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200328_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='activity_periods',
        ),
        migrations.AddField(
            model_name='member',
            name='activity_periods',
            field=models.ManyToManyField(to='member.time'),
        ),
    ]
